#! /bin/bash

# initialize git repository
git init

# initialize gitignore file
cat <<EOF > .gitignore
node_modules
.eslintcache
EOF

# initialize yarn project
yarn init

# add eslint & prettier as dev dependencies
yarn add --dev eslint prettier eslint-config-prettier

# run eslint project initializer
npx eslint --init

# remove package-lock.json generated by npm for consistency with yarn
rm package-lock.json
yarn

# set eslint config file name based on user selection (json or javascript)
ESLINT_CONFIG_FILE='.eslintrc.json'
if [ -f ./.eslintrc.js ]
then
  ESLINT_CONFIG_FILE='.eslintrc.js'
fi

# customize eslint config file
node > out_${ESLINT_CONFIG_FILE} <<EOF
const data = require('./${ESLINT_CONFIG_FILE}');
data.extends = data.extends ? [...data.extends, 'prettier'] : ['prettier'];
if('${ESLINT_CONFIG_FILE}'==='.eslintrc.js'){
  console.log('module.export = ' + JSON.stringify(data));
} else {
  console.log(JSON.stringify(data));
}
EOF
mv out_${ESLINT_CONFIG_FILE} ${ESLINT_CONFIG_FILE}

# initialize prettier config file
cat <<EOF > .prettierrc
{
  "singleQuote": true
}
EOF

# add lint-staged precommit hook
npx mrm@2 lint-staged

# customize the package.json file
node > out_package.json <<EOF
const data = require('./package.json');
data['lint-staged'] = {
  "**/*.{js,ts,jsx,tsx}": ["eslint --cache --fix", "prettier --write"],
  "**/*.{css,scss,json}": "prettier --write"
}
console.log(JSON.stringify(data));
EOF
mv out_package.json package.json

# reformat all
yarn run prettier --write .

# remove the current script
rm javascript_initializer.sh